models.py
from app import db
from datetime import datetime
import re


# получаем строку ЧПУ для URL
def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

# Связь "посты-тэги" мгоие ко многим
post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),  # id поста
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))  # id тэга
                     )

# БД постов
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    # подключаем ЧПУ
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    # получаем аргументы которые передали на вход конструктора
    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        # получаем URL от функции
        self.generate_slug()

    # функция генерации URL из заголовка для ЧПУ
    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    # формируем удобочитаемую строку с данными
    def __repr__(self):
        return '<Post: id: {}, title: {}>'.format(self.id, self.title)

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))


# класс для обработки тэгов
class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))  # название тэга
    slug = db.Column(db.String(100))  # URL ЧПУ для вывода результата

    def __init__(self, *args, **kwargs):  # получаем аргуементы, которые ищем списком
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)  # формируем ЧПУ для них

    def __repr__(self):  # формируем удобочитаемую строку с данными
        return '<Tag id: {}, name: {}>'.format(self.id, self.name)

app.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from config import Config

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager


# обращаемся к приложению
app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


@app.route('/')
def index():
    return render_template('index.html')

main.py
from app import app
from app import db
from posts.blueprint import posts  # blueprint постов

app.register_blueprint(posts, url_prefix='/blog')  # посты в папке "posts" с адресом "/blog"

# запускаем приложение
# делаем это тут, потому что если сделать это в "app.pv"
# то будет круговое импортирование между "blueprint" и "app"
#  из-за класса "import Post" который в "blueprint" подключается
if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post

posts = Blueprint('posts', __name__, template_folder='templates')


# выводим список постов
# localhost/blog/
@posts.route('/')
def index():
    blog_posts = Post.query.all()
    return render_template('posts/index.html', posts=blog_posts)


# выводим детальную карточку постов
# localhost/blog/name_post
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()  # это временная мера, тут нужна проверка уникальности
    return render_template('posts/post_detail.html', post=post)

posts/templates/posts/index.html
{% extends "base.html" %}

{% block title %}
    Тестовые посты blueprint
{% endblock %}

{% block content %}

    <div class="container">

        {# выводим посты #}
        {% for post in posts %}
            <p>
                 <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
                     {{ post.title }}
                 </a>
            </p>
        {% endfor  %}

    </div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}

    <div class="container">

        {{ post.body }}

    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/css/template_styles.css" />
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
<div id="app"></div>
<div class="header">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-2">
                <a class="logo" href="{{ url_for('index') }}"></a>
            </div>
            <div class="col-md-8">
                <div class="h__title">
                    <h1>Росгвардия</h1>
                </div>
                <div class="h__descr">
                    Ну типа пробная CMS, что-то попытался
                </div>
            </div>
            <div class="col-md-2">
                 <input type="submit" class="vecdev-btn white-btn vecdev--showcb" value="Залогиниться" />
            </div>
        </div>
    </div>
</div>
<div class="main-menu">
    <div class="container">
         <ul>
            <li>
                <a href="{{ url_for('posts.index') }}">Новости</a>
            </li>
        </ul>
    </div>
</div>
<div class="content">
   {% block content %}

    {% endblock %}
</div>
<div class="vecdev-cb vecdev-cb--onshow">
    <div class="vecdev-cbform__bg vecdev-cb--onhide"></div>
    <div class="vecdev-cbform">
        <span class="vecdev-close vecdev-cb--onhide"></span>
        <div class="vecdev-cb__title">Заполните форму</div>
        <div class="form-group">
            <label for="cb-email">Введите Логин</label>
            <input type="email" class="vecdev-input" id="cb-email" placeholder="name@example.com">
        </div>
        <div class="form-group">
            <label for="cb-phone">Пароль</label>
            <input type="text" class="vecdev-input" id="cb-phone" placeholder="+7 (999) 999-99-99">
        </div>
        <div class="form-group text-center">
            <input class="vecdev-btn red-btn" type="submit" value="Вход" data-toggle="modal" data-target="#exampleModalCenter" onclick="sendMail()">
        </div>
    </div>
</div>
<script src="/static/js/jquery-3.4.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/myscripts.js"></script>
<script src="/static/js/vue.js"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
12313
{% endblock %}

    {% block content %}
        <div class="container">
            12312312
        </div>
    {% endblock %}